### ISSUE TITLE
可滑动支持

### ISSUE THREAD

**Issue by Kado814** [asundust/NAS-Nav-iCloud#4]
地址添加多了，不能滑动

**Comment by asundust** [comment]
`index.html`文件下的`body`下(在20行左右)添加`overflow-y: auto;`属性即可
![image](https://github.com/asundust/NAS-Nav-iCloud/assets/6573979/8161c912-9252-469b-921c-24ee43f67bed)

**Comment by Kado814** [comment]
> `index.html`文件下的`body`下(在20行左右)添加`overflow-y: auto;`属性即可 ![image](https://user-images.githubusercontent.com/6573979/260359248-8161c912-9252-469b-921c-24ee43f67bed.png)

![image](https://github.com/asundust/NAS-Nav-iCloud/assets/10460173/8cbf3252-ef97-4586-8121-169246a29bbf)
有滚动条了，但是内容显示不完

**Comment by asundust** [comment]
把修改方案换成如下：
``` css
#wrap::-webkit-scrollbar {
    width: 0;
}
#wrap {
    overflow-y: auto;
}
```
![image](https://github.com/asundust/NAS-Nav-iCloud/assets/6573979/534e0184-a0d9-4fd8-a86c-42075dd4187b)
